name: Build and Publish
on:
  release:
    types: [ published ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout modpack repo
        uses: actions/checkout@v4
        with:
          path: modpack
      - name: Inject modpack version
        run: jq --arg value "${{ github.event.release.tag_name }}" '.versionId = $value' modpack/modrinth.index.json > modrinth.index.json && mv modrinth.index.json modpack/modrinth.index.json
      - name: Pack mrpack
        run: cd modpack && zip -r ../xisumas-hermitcraft-pack.mrpack modrinth.index.json overrides/
      - name: Upload mrpack
        uses: actions/upload-artifact@v4
        with:
          name: xisumas-hermitcraft-pack
          path: xisumas-hermitcraft-pack.mrpack
      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: xisumas-hermitcraft-pack.mrpack
          name: Xisuma's Hermitcraft Pack ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          game_versions: 1.21.4
          loaders: fabric
          release_type: alpha
          featured: true
          project_id: TRGgrV7V